controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


scara_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_3
      - joint_6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

# Controller này đang thực hiện 
# + Lệnh đầu vào là điều khiển vị trí của robot
# + Lệnh phản hồi cho Rviz2 và controller
#   + Ví trí và vận tốc